apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
  containers:
    - command: ["sleep", "3600"]
      image: busybox
      name: container
  tolerations:
    - key: "pod-toleration"  # empty means match all taint keys
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 0