apiVersion: v1
kind: Pod
metadata:
  name: toleration
spec:
  containers:
    - command: ["sleep", "3600"]
      image: busybox
      name: container
  tolerations:
    - key: "pod-toleration"  # empty means match all taint keys
      operator: "Exists"
      effect: "NoExecute"
      tolerationSeconds: 0 # By default, it is not set, which means tolerate the taint forever (do not evict). Zero and negative values will be treated as 0 (evict immediately) by the system.