apiVersion: v1
kind: Pod
metadata:
  name: nodeselector
spec:
  containers:
    - command: ["sleep", "3600"]
      image: busybox
      name: container
  nodeSelector:
    node-role.kubernetes.io/master: ""